### PR TITLE
empty list welcome message/link and submit token input changed to a form

### LINKED ISSUE #7: 7. As a user, I want to see a welcoming prompt to add my first item if my list is empty to help me get oriented to how the app works.
AC:

* The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item
Notes:
* The wireframe is a little short on the "welcoming" part of the story, but otherwise is functionally complete for the purposes of the AC. https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/list-empty.png

### PR DESCRIPTION
**Pull request by colefortner**
## Description

Displays message with link to prompt user to add item if no items exist in list.
Converts token input on landing page to a form to improve accessibility.

## Related Issue

closes #7 

## Acceptance Criteria

- [x] The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓ | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |

### Before

When list is empty, user sees 'Your Items' and the token 
Screen Shot 2022-04-25 at 9 36 29 PM

### After

When list is empty, user sees message prompting them to add an item along with a link that will take them to the form where they can add items
Screen Shot 2022-04-25 at 10 04 17 PM

### Issue

- From your terminal, pull down this branch with `git pull origin jc-cf-empty-list-welcome-prompt` and check that branch out with `git checkout jc-cf-empty-list-welcome-prompt`.
- Check that when you click on the 'create a new list' button that it redirects user to the '/item-list' route and user sees the message 'Your Shopping list is currently empty' along with a link to the Add Item Form.
- Click the 'Add an Item' link, then the 'List of Items' link to go back, check for the same message and link as before.
- Click the 'Add an Item' link, add an item to your shopping list, click 'List of Items' link.  User should see the header 'Your Items', the user token, and any items added to the list.

### Refactor

- Logout from the previous Issue test.
- Try joining a list with an empty token field.  A box should pop up  from token field that says 'Please fill out this field'.
- Try joining a list using random characters in token field.  An alert should pop up that says 'token does not exist'.
- Try joining a list with `fond aloof slap` in token field.  User should be redirected to an existing list associated with that token.

### CODE REVIEW

**Comment by honzlavender** [comment]
Looks great! I love a rendered ternary operator  💫

**Review by HonduranCoder — APPROVED** [review]
Functionality: AC completed. Good Job.
The Setup/Documentation: Thoroughly done, appreciate the extensiveness. 
Consistency: Code looks clean

**Review by honzlavender — APPROVED** [review]
Approved!

**Review by MikeBLambert — APPROVED** [review]
Works great and wonderful job adding that missing `<form />`!!!

**Pull request merged**
